version: "3"

services:
  postgres:
    image: postgres:15.4
    container_name: bestfilms_psql
    restart: always
    # env_file:
    #   - .env
    environment:
      DB_HOST: 0.0.0.0
      POSTGRES_DB: BESTFILMS
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      PGDATA: /var/lib/postgresql/data
    volumes:
       - bestfilms_db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 15s
      timeout: 5s
      retries: 3 

  pgadmin:
    container_name: bestfilms_pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 12345
    ports:
      - 5050:80

volumes:
  bestfilms_db:
    